version: '3'
services:
  app:
    image: perelo96/coinmarketcap_cripto_info
    environment:
      - API_KEY=COINMARKETCAP_API_KEY
      - SYMBOLS=SYMBOLS_TO_FOLLW
      - TELEGRAM_API_TOKEN=YOUR_TELEGRAM_API_TOKEN
      - TELEGRAM_CHAT_ID=YOUR_TELEGRAM_CHAT_ID
